# Generated by Django 2.2.3 on 2019-08-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rajarancho', '0002_auto_20190826_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldata',
            name='name',
        ),
    ]
