# Generated by Django 2.2.3 on 2019-08-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspots',
            name='content1',
            field=models.TextField(default='', max_length=25500),
        ),
        migrations.AlterField(
            model_name='blogspots',
            name='content2',
            field=models.TextField(default='', max_length=25500),
        ),
        migrations.AlterField(
            model_name='blogspots',
            name='heading1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogspots',
            name='heading2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogspots',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
