# Generated by Django 2.2.3 on 2019-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190805_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspots',
            name='images',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogspots',
            name='thumbnils',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='images',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
