# Generated by Django 2.2.3 on 2019-08-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190807_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspots',
            name='title',
            field=models.CharField(default='Dont Used % ,*,+,-,#,@,^,& in title', max_length=300),
        ),
    ]
