# Generated by Django 2.2.3 on 2019-08-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190819_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspots',
            name='keywords',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
