# Generated by Django 2.2.3 on 2019-08-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_blogspots_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspots',
            name='images',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogspots',
            name='thumbnils',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogspots',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogspots',
            name='title',
            field=models.CharField(error_messages={'required': 'Please enter your name'}, max_length=300),
        ),
    ]
