# Generated by Django 2.2.3 on 2019-08-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190823_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspots',
            name='images',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogspots',
            name='thumbnils',
            field=models.FileField(upload_to=''),
        ),
    ]
